### ISSUE TITLE
how do i use this

### ISSUE THREAD

**Issue by raytran** [aidan-dc/L1BTag#1]
thanks

**Comment by raytran** [comment]
help

**Comment by aidan-dc** [comment]
Hi Raymond I've added some miniature datasets [here](https://github.com/aidan-dc/L1BTag/blob/d33c5d308d4e01ed0e8f7d28c0788c79f3429a87/pfTuple.root) and [here](https://github.com/aidan-dc/L1BTag/blob/d33c5d308d4e01ed0e8f7d28c0788c79f3429a87/pfTuple_1.root) that can be run with a dataForge script. These are TTBar event simulation datasets so I'd recommend using this [one](https://github.com/aidan-dc/L1BTag/blob/d33c5d308d4e01ed0e8f7d28c0788c79f3429a87/dataForgeScripts/dataForge.py) since there's no reason to group jets by event. This should produce a small dataset you can use to try out training a network either using [this Keras training script](https://github.com/aidan-dc/L1BTag/blob/d33c5d308d4e01ed0e8f7d28c0788c79f3429a87/kerasModel.py) or any NN/deep learning architecture of your choice. I can't promise the results will be very good with a small dataset, but you can use [this file](https://github.com/aidan-dc/L1BTag/blob/d33c5d308d4e01ed0e8f7d28c0788c79f3429a87/ROC.py) to produce a Receiver Operating Characteristic curve to evaluate your network performance or [this script](https://github.com/aidan-dc/L1BTag/blob/main/effCurve.py) to evaluate your network's performance as a function of key physical variables.

You'll need ROOT/PyROOT (the CERN/CMS software not the Linux password authority) to run any of these scripts so import that library using whatever method you prefer.

Alternatively if you don't want to import ROOT libraries or use these datasets you can replicate the amazing efficiency of my code using the following script:

`while True: print('yes')`
